/**
 * Industry brand presets for 1-click campaign generation
 */
export const INDUSTRY_PRESETS = [
  {
    id: 'skincare',
    name: '🧴 GlowSkin Serum',
    category: 'Beauty & Skincare',
    businessName: 'Lumina Glow',
    product: 'Vitamin C Brightening Serum with Niacinamide that eliminates dark spots in 14 days',
    audience: 'Women 20-35 dealing with hyperpigmentation and dull skin',
    platform: 'tiktok',
    framework: 'bab',
    tone: 'authentic',
    duration: '30s',
    language: 'en',
    painPoint: 'stubborn acne scars and dull skin that makeup cannot hide',
    offer: 'GLOW20'
  },
  {
    id: 'saas',
    name: '🚀 FocusFlow AI',
    category: 'Productivity SaaS',
    businessName: 'FocusFlow AI',
    product: 'AI task manager that auto-schedules your day and eliminates calendar conflicts',
    audience: 'Remote tech workers, founders, and busy freelancers',
    platform: 'instagram',
    framework: 'pas',
    tone: 'genz',
    duration: '60s',
    language: 'en',
    painPoint: 'spending 2 hours every morning just sorting through chaotic to-do lists',
    offer: 'FLOWPRO'
  },
  {
    id: 'fitness',
    name: '⌚ PulseBand Pro',
    category: 'Fitness Tech',
    businessName: 'PulseActive',
    product: 'Waterproof smart fitness band with continuous biometric recovery tracking',
    audience: 'Crossfit athletes and health-conscious gym goers',
    platform: 'youtube',
    framework: 'mythbuster',
    tone: 'controversial',
    duration: '60s',
    language: 'en',
    painPoint: 'overtraining and guessing workout recovery without scientific data',
    offer: 'FIT30'
  },
  {
    id: 'coffee',
    name: '☕ ColdBrew Labs',
    category: 'Food & Beverage',
    businessName: 'ColdBrew Labs',
    product: 'Ultra-smooth nitrogen infused nitro cold brew concentrate delivered in 1-liter boxes',
    audience: 'Coffee enthusiasts wanting café quality cold brew at home under 30 seconds',
    platform: 'tiktok',
    framework: 'unboxing',
    tone: 'humorous',
    duration: '30s',
    language: 'en',
    painPoint: 'spending $7 every single day waiting in long café drive-thru lines',
    offer: 'BREWME'
  },
  {
    id: 'tamil_creator',
    name: '🇮🇳 Tamil Creator Hub',
    category: 'EdTech / Tamil',
    businessName: 'SkillTamil Pro',
    product: 'Tamil language AI coding and video editing bootcamp with live mentorship',
    audience: 'College students and career switchers in Tamil Nadu looking for IT jobs',
    platform: 'instagram',
    framework: 'pas',
    tone: 'authentic',
    duration: '60s',
    language: 'ta',
    painPoint: 'English-only tutorials puriyaama coding kathukka kashtapadradhu',
    offer: 'TAMIL50'
  },
  {
    id: 'fashion',
    name: '👗 StyleDrop Fashion',
    category: 'E-Commerce Fashion',
    businessName: 'StyleDrop',
    product: 'Sustainable minimalist clothing line made from organic cotton — designed to last 10+ years',
    audience: 'Fashion-conscious millennials who hate fast fashion and want to build a capsule wardrobe',
    platform: 'instagram',
    framework: 'confession',
    tone: 'authentic',
    duration: '30s',
    language: 'en',
    painPoint: 'buying cheap clothes that shrink, fade, and fall apart after 3 washes',
    offer: 'CAPSULE15'
  },
  {
    id: 'supplement',
    name: '💊 VitalBoost Collagen',
    category: 'Health & Wellness',
    businessName: 'VitalBoost',
    product: 'Marine Collagen + Hyaluronic Acid powder blend for joint recovery and glowing skin',
    audience: 'Active women over 30 dealing with joint stiffness and visible skin aging',
    platform: 'facebook',
    framework: 'bab',
    tone: 'high_ticket',
    duration: '60s',
    language: 'en',
    painPoint: 'morning joint stiffness and skin that no longer bounces back like it used to',
    offer: 'VITAL30'
  },
  {
    id: 'hindi_creator',
    name: '🇮🇳 Hindi Creator Kit',
    category: 'Creator Tools / Hinglish',
    businessName: 'ContentKing India',
    product: 'Complete video editing + thumbnail design course in Hindi for aspiring YouTube creators',
    audience: 'Hindi-speaking youth aged 18-28 who want to earn from YouTube but don\'t know where to start',
    platform: 'youtube',
    framework: 'mythbuster',
    tone: 'genz',
    duration: '60s',
    language: 'hi',
    painPoint: 'channel grow nahi ho raha aur editing sikhne ke liye English tutorials samajh nahi aate',
    offer: 'KING50'
  }
];
